;引擎基础配置文件@XUEWU 本文件存放服务端tlbb的位置:/Server/Config/下
;注意和V2.3还是2.4这个和帖子写的对应,自己改一下,不然无法启动

[Disclaimer]
Notice=公开版本@仅供学习交流，严禁用于商业用途，请于24小时内删除,当前版本SOV2.7_DLLV2.0-@XUEWU_2026-3-1

[Waylee]
XueWuQQ=784055837	#雪舞的QQ是多少(请勿删除修改此项目)

[BindShop]
AllowYuanBaoBuyBindYuanShopItems=1	;开启绑定元宝不足元宝补足(1允许0拒绝)
BindYuanShopItemsAreBind=1         ;绑定元宝商店购买的商品是否绑定(1绑定0不绑定)
[GoodsProtect_Goods]
AllowDropAndSell=1   ;1=允许丢弃/出售受贵重物品, 0=保持原有保护逻辑
[WuJing]
MaxDamageRefix=5   ; 武境增伤/减伤百分比最大修正值
[timestamp]
Subtime=347155200	;将服务器时间回退指定的秒数
[Time]
SendRealTime=1      ;时间不同步问题
[NewExterior]
ExteriorWeaponExt=1 ;是否开启幻饰武器扩展至255个
[ShareMem]
KeyCount=1
Key0=1163416663
Type0=15   ;ExtWeaponSMU
Interval0=0
;回调类
[SkillCallback]
EnableSkillRadiusCallback=1
EnableIsHitCallback=1
EnableIsCriticalHitCallback=1
EnableScanTargetCallback=1
[LevelUpCallback]
EnableLevelUpCheckCallback=1
[ImpactCallback]
EnableStdImpact005Callback=1
EnableStdImpact009Callback=1
EnableStdImpact010Callback=1
[SpecialCallback]
EnableSpecialFadeInCallback=1
[ExchangeCallback]
EnableExchangeConfirmationCallback=1
[ImpactRegisterCallback]
EnableImpactRegisterCallback=1
[GuildCallback]
EnableCreatGuildCallback=1
[PetCallback]
EnableHumanPetDieCallback=1
[ChatCallback]
EnableClientMsgCallback=1
EnableChatMsgCallback=1
[SkillStartCallback]
EnableSkillStartCallback=1
[DropCallback]
EnableMonsterDropCallback=1  ; 0=关闭, 1=开启怪物掉落回调(概率callback_MonsterDrop)
EnableItemDropCallback=1     ; 0=关闭, 1=开启物品掉落回调(物品callback_ItemDrop)
;强化等级上限
[Enhance]
MaxEnhanceLevel=99
[MoveSpeed]
MaxMoveSpeed=50   ; 移动速度上限 (范围20~200, 默认20)
[TLBBVersion]
Version=1650
[Combat]
DefaultChuanCiDmageEnlarge=100	;缺省穿刺攻击修正百分比系数
ChuanCiHumanEnlarge= 100		;穿刺攻击人物修正百分比系数
ChuanCiMasterEnlarge= 100		;穿刺攻击怪物修正百分比系数
ChuanCiPetEnlarge= 0			;穿刺攻击宠物修正百分比系数
DefaultQieGeDmageEnlarge=100    ;缺省切割攻击修正百分比系数
QieGeHumanEnlarge=100           ;切割攻击人物修正百分比系数
QieGeMasterEnlarge=100          ;切割攻击怪物修正百分比系数
QieGePetEnlarge=0               ;切割攻击宠物修正百分比系数
;重楼套装BUFF启用否
[SuitBuff]
EnableSuitBuff=1
[CityShop]
DefaultBuildingLevel=5